name = "backend"
compatibility_date = "2024-07-16"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjc3ZWUyZjYtOTcyYy00MjFjLTg1ZGEtZGRlYmQ5NmM3NDAwIiwidGVuYW50X2lkIjoiYWVmZDJiOWUxMjVhN2NkNTEwYzY4ZGVjNDIwMGFhMzdlNDk2ODgwZWMyMWI0MjA1YTZmODlhMjNjNTY4ZGZlYiIsImludGVybmFsX3NlY3JldCI6IjNmYmU5MzUyLTk1YzYtNDZhNi1hOTk0LTg3YmE2MTYxMzI5ZSJ9.NEEbXQaEcXTsKxnAH5eURXdhaxZmFKZo0BCxkRAzAmw"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"